import Head from "next/head";

import Image from "next/image";
import Bar from "../components/Bar";

export default function Home() {
  const barValues = [
    { title: "mon", value: "30" },
    { title: "tue", value: "70" },
    { title: "wed", value: "100" },
    { title: "thu", value: "60" },
    { title: "fri", value: "40" },
    { title: "sat", value: "80" },
    { title: "sun", value: "50" },
  ];

  return (
    <div className="px-2">
      <Head>
        <title>Expenses Chart Component</title>
        <meta name="description" content="Generated by Mike van Peeren" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-2 flex flex-col justify-center items-center min-h-screen">
        <div className="flex flex-col rounded-xl gap-4">
          <div className="rounded-xl bg-red flex flex-row items-end justify-between text-white px-4 py-4">
            <div className="flex flex-col pr-32">
              <h1 className="text-xs">My Balance</h1>
              <span className="text-xl">$921.48</span>
            </div>
            <div>
              <Image alt="" src="/logo.svg" width={72} height={48} />
            </div>
          </div>
          <div className="bg-veryPaleOrange rounded-xl  px-4 py-4">
            <h2 className="text-darkBrown font-bold tracking-wide">
              Spending - Last 7 days
            </h2>
            <div className="flex flex-row gap-3 mt-4">
              {barValues.map((barValue) => {
                return (
                  <Bar
                    key={barValue.title}
                    title={barValue.title}
                    value={barValue.value}
                  />
                );
              })}
            </div>
            <hr className="my-4 bg-cream text-red h-0.5 border-none rounded-xl" />
          </div>
        </div>
      </main>
    </div>
  );
}
